=== z718713192/MyOther/oracle/DbVisualizer/resources/profiles/dbvis-defs.dtd
<?xml version="1.0" encoding="UTF-8" ?>

<!--
   @(#)$Id: dbvis-defs.dtd 14895 2012-06-16 09:40:15Z rogge $

   Copyright (c) 2010 DbVis Software AB. All Rights Reserved.
-->

<!-- =================================================================== -->
<!-- DTD for database profile XML documents in DbVisualizer -->
<!-- =================================================================== -->

<!-- DatabaseProfile -->

<!ELEMENT DatabaseProfile (InitCommands | Commands | ObjectsActionDef | ObjectsTreeDef | ObjectsViewDef)*>
<!ATTLIST DatabaseProfile name CDATA #IMPLIED
                          desc CDATA #IMPLIED
                          version CDATA #IMPLIED
                          minver CDATA #IMPLIED
                          date CDATA #IMPLIED>

<!-- If, ElseIf, Else -->
<!ELEMENT If (#PCDATA | If | ElseIf | Else | Command | Filter | SQL | Input | Output | Column | DataNode | GroupNode | SetVar | ObjectView | DataView | Message | ActionGroup | Action | Separator | Arg)*>
<!ATTLIST If test CDATA #REQUIRED
             context (load | runtime) #IMPLIED>

<!ELEMENT ElseIf (#PCDATA | If | ElseIf | Else | Command | Filter | SQL | Input | Output | Column | DataNode | GroupNode | SetVar | ObjectView | DataView | Message | ActionGroup | Action | Separator | Arg)*>
<!ATTLIST ElseIf test CDATA #REQUIRED
                 context (load | runtime) #IMPLIED>

<!ELEMENT Else (#PCDATA | If | ElseIf | Else | Command | Filter | SQL | Input | Output | Column | DataNode | GroupNode | SetVar | ObjectView | DataView | Message | ActionGroup | Action | Separator | Arg)*>

<!-- Commands -->
<!ELEMENT InitCommands (OnError | Command | If | ElseIf | Else)*>
<!ELEMENT Commands (OnError | Command | If | ElseIf | Else)*>

<!ELEMENT Command (Output | Input | SQL | Filter | OnError | If | ElseIf | Else)*>
<!ATTLIST Command id ID #IMPLIED
                  idref IDREF #IMPLIED
                  method (jdbc | dynamic | runBeforeConditionsEval) #IMPLIED
                  parsesql (true | false) #IMPLIED
                  continueonerror (true | false) #IMPLIED>

<!-- OnError -->
<!ELEMENT OnError (Message | If | ElseIf | Else)*>
<!ATTLIST OnError type (extend | replace) #IMPLIED>

<!-- Filter -->
<!ELEMENT Filter (Column | If | ElseIf | Else)*>
<!ATTLIST Filter type CDATA #IMPLIED
                 name CDATA #IMPLIED>

<!-- ObjectsActionDef -->

<!ELEMENT ObjectsActionDef (ActionGroup | If | ElseIf | Else)*>

<!-- ObjectsTreeDef -->

<!ELEMENT ObjectsTreeDef (DataNode | GroupNode | If | ElseIf | Else)*>
<!ATTLIST ObjectsTreeDef id CDATA #REQUIRED>

<!ELEMENT DataNode (SetVar | Command | DataNode | GroupNode | If | ElseIf | Else)*>
<!ATTLIST DataNode type CDATA #REQUIRED
                   actiontype CDATA #IMPLIED
                   label CDATA #REQUIRED
                   sort CDATA #IMPLIED
                   stop-label-not-equal CDATA #IMPLIED
                   drop-label-not-equal CDATA #IMPLIED
                   is-empty-output (continue | stop) #IMPLIED
                   isLeaf CDATA #IMPLIED
                   warnstate CDATA #IMPLIED
                   errorstate CDATA #IMPLIED>

<!ELEMENT SetVar (#PCDATA | If | ElseIf | Else)*>
<!ATTLIST SetVar name CDATA #REQUIRED
                 value CDATA #IMPLIED
                 action (show | hide | drop) #IMPLIED>

<!ELEMENT GroupNode (DataNode | GroupNode | If | ElseIf | Else)*>
<!ATTLIST GroupNode type CDATA #REQUIRED
                    label CDATA #REQUIRED
                    drop-label-not-equal CDATA #IMPLIED                    
                    isLeaf CDATA #IMPLIED>

<!-- ObjectsViewDef -->

<!ELEMENT ObjectsViewDef (ObjectView | If | ElseIf | Else)*>
<!ATTLIST ObjectsViewDef id CDATA #REQUIRED
                         extends CDATA #IMPLIED>

<!ELEMENT ObjectView (DataView | If | ElseIf | Else)*>
<!ATTLIST ObjectView type CDATA #REQUIRED
                     action (add | delete) #IMPLIED>

<!ELEMENT DataView (DataView | Input | Action | Command | Message | If | ElseIf | Else)*>
<!ATTLIST DataView type CDATA #REQUIRED
                   label CDATA #IMPLIED
                   viewer CDATA #IMPLIED
                   drop-label-not-equal CDATA #IMPLIED
                   class CDATA #IMPLIED
                   classargs CDATA #IMPLIED
                   action (add | drop) #IMPLIED
                   doclink CDATA #IMPLIED>

<!-- Common elements -->

<!ELEMENT Message (#PCDATA | If | ElseIf | Else)*>
<!ELEMENT Confirm (#PCDATA | If | ElseIf | Else)*>
<!ELEMENT Result (#PCDATA | If | ElseIf | Else)*>
<!ELEMENT Values (#PCDATA | Command | If | ElseIf | Else)*>
<!ATTLIST Values column CDATA #IMPLIED>
<!ELEMENT Labels (#PCDATA | Command | If | ElseIf | Else)*>
<!ATTLIST Labels column CDATA #IMPLIED>
<!ELEMENT Default (#PCDATA | Command | If | ElseIf | Else)*>
<!ATTLIST Default column CDATA #IMPLIED>

<!ELEMENT ActionGroup (ActionGroup | Action | Separator | If | ElseIf | Else)*>
<!ATTLIST ActionGroup type CDATA #IMPLIED
                      label CDATA #IMPLIED>

<!ELEMENT Separator (#PCDATA)*>

<!ELEMENT Action (Command | Confirm | SQL | Result | Input | SetVar | If | ElseIf | Else)*>
<!ATTLIST Action name CDATA #IMPLIED
                 id ID #IMPLIED
                 icon CDATA #IMPLIED
                 label CDATA #IMPLIED
                 processmarkers (true | false) #IMPLIED
                 reload (true | false) #IMPLIED
                 resetcatalogs (true | false) #IMPLIED
                 resetschemas (true | false) #IMPLIED
                 supportsmultipleobjects (true | false) #IMPLIED
                 class CDATA #IMPLIED
                 classargs CDATA #IMPLIED
                 mode (execute | script | script-immediate) #IMPLIED
                 resulttype (resultset | dbmsoutput) #IMPLIED
                 resultaction (ask | show | script) #IMPLIED
                 doclink CDATA #IMPLIED
                 hideif CDATA #IMPLIED>

<!ELEMENT Arg (#PCDATA | If | ElseIf | Else)*>
<!ATTLIST Arg name CDATA #REQUIRED
              value CDATA #REQUIRED>

<!ELEMENT SQL (#PCDATA | If | ElseIf | Else)*>

<!ELEMENT Input (Column | Values | Labels | Default | Input | Arg | If | ElseIf | Else | SetVar)*>
<!ATTLIST Input label CDATA #IMPLIED
                name CDATA #IMPLIED
                value CDATA #IMPLIED
                tip CDATA #IMPLIED
                editable (true | false) #IMPLIED
                linebreak (true | false) #IMPLIED
                style (list | radio | text | check | password | number | text-editor | grid | separator) #IMPLIED
                hideif CDATA #IMPLIED>

<!ELEMENT Output (If | ElseIf | Else)*>
<!ATTLIST Output id CDATA #IMPLIED
                 index CDATA #IMPLIED
                 name CDATA #IMPLIED
                 value CDATA #IMPLIED
                 modelaction CDATA #IMPLIED>

<!ELEMENT Column (If | ElseIf | Else)*>
<!ATTLIST Column id CDATA #IMPLIED
                 index CDATA #IMPLIED
                 name CDATA #IMPLIED
                 value CDATA #IMPLIED
                 modelaction CDATA #IMPLIED>

=== z718713192/MyOther/oracle/DbVisualizer/resources/profiles/postgresql8.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE DatabaseProfile SYSTEM "dbvis-defs.dtd" [
   <!ENTITY generic-commands SYSTEM "generic-commands.xml">
   <!ENTITY generic-view SYSTEM "generic-view.xml">
   ]>

<!--
   Copyright (c) DbVis Software AB. All Rights Reserved.
-->

<DatabaseProfile
   desc="Profile for PostgreSQL 8+"
   version="$Revision: 14998 $"
   date="$Date: 2012-07-18 10:53:12 +0200 (Wed, 18 Jul 2012) $"
   minver="7.1">

   <!--
    Profile Notes
    =============
      None.

    Change Log
    ==========
      2009-05-27:
        - Fix for PostgreSQL 8.4 (reltriggers renamed to hasreltriggers in pg_class)
      2007-09-11:
        - Now show Columns and Indexes as child objects for Table objects
      2007-05-20:
        - Comment info is now fetched in getSchemas, getTables, getViews, getIndexes
        - Now possible to set comment on Schema, Table, View, Index, Sequence
      2006-09-18:
        - Added "Empty Table" action for table nodes
   -->

   <!-- =================================================================== -->
   <!-- Definition of the commands -->
   <!-- =================================================================== -->

   <Commands>

      &generic-commands;

      <Command id="postgresql.getCatalogs">
         <SQL>
            <![CDATA[
select * from pg_catalog.pg_database
            ]]>
         </SQL>
      </Command>


      <Command id="postgresql.getSchemas">
         <SQL>
            <![CDATA[
SELECT n.nspname                                         AS "Name",
       r.usename                                         AS "Owner",
       pg_catalog.obj_description(n.oid, 'pg_namespace') AS "Comment"
FROM pg_catalog.pg_namespace n
   LEFT JOIN pg_catalog.pg_user r ON n.nspowner= r.usesysid
ORDER BY 1
            ]]>
         </SQL>
      </Command>

      <Command id="postgresql.getTables">
         <SQL>
            <![CDATA[
SELECT c.relname                                     AS "Name",
       n.nspname                                     AS "Schema",
       pg_get_userbyid(c.relowner)                   AS "Owner",
       t.spcname                                     AS "Tablespace",
       c.relhasindex                                 AS "Has Indexes",
       c.relhasrules                                 AS "Has Rules",
       ]]>
       <If test="(#dm.getDatabaseMajorVersion() gte 8 and
                  #dm.getDatabaseMinorVersion() gte 4) or
                  #dm.getDatabaseMajorVersion() gte 9">
       <![CDATA[
       c.relhastriggers                               AS "Has Triggers",
       ]]>
       </If>
       <Else>
       <![CDATA[
       (c.reltriggers > 0)                            AS "Has Triggers",
       ]]>
       </Else>
       <![CDATA[
       c.relisshared                                 AS "Is Shared",
       c.relnatts                                    AS "N Cols",
       pg_catalog.obj_description(c.oid, 'pg_class') AS "Comment"
FROM   pg_class c
   LEFT JOIN pg_namespace n   ON n.oid = c.relnamespace
   LEFT JOIN pg_tablespace t  ON t.oid = c.reltablespace
WHERE c.relkind = 'r'::"char"
AND   n.nspname LIKE '${schema}'
AND   c.relname LIKE '${table}'
ORDER BY n.nspname, c.relname
            ]]>
         </SQL>
      </Command>

<!--
      <Command id="postgresql.getTable">
         <SQL>
            <![CDATA[
select * from pg_tables where tablename = '${table}'
            ]]>
         </SQL>
      </Command>
-->

      <Command id="postgresql.getViews">
         <SQL>
            <![CDATA[
SELECT c.relname                                      AS "Name",
       n.nspname                                      AS "Schema",
       pg_get_userbyid(c.relowner)                    AS "Owner",
       t.spcname                                      AS "Tablespace",
       c.relhasindex                                  AS "Has Indexes",
       c.relhasrules                                  AS "Has Rules",
       ]]>
       <If test="(#dm.getDatabaseMajorVersion() gte 8 and
                  #dm.getDatabaseMinorVersion() gte 4) or
                  #dm.getDatabaseMajorVersion() gte 9">
       <![CDATA[
       c.relhastriggers                               AS "Has Triggers",
       ]]>
       </If>
       <Else>
       <![CDATA[
       (c.reltriggers > 0)                            AS "Has Triggers",
       ]]>
       </Else>
       <![CDATA[
       c.relisshared                                  AS "Is Shared",
       c.relnatts                                     AS "N Cols",
       pg_catalog.obj_description(c.oid, 'pg_class')  AS "Comment"
FROM   pg_class c
   LEFT JOIN pg_namespace n   ON n.oid = c.relnamespace
   LEFT JOIN pg_tablespace t  ON t.oid = c.reltablespace
WHERE c.relkind = 'v'::"char"
AND   n.nspname LIKE '${schema}'
AND   c.relname LIKE '${table}'
ORDER BY n.nspname, c.relname
            ]]>
         </SQL>
      </Command>

      <Command id="postgresql.getIndexes">
         <SQL>
            <![CDATA[
SELECT i.relname                                             AS "Index Name",
       n.nspname                                             AS "Schema Name",
       c.relname                                             AS "Table Name",
       t.spcname                                             AS "Tablespace",
       x.indisunique                                         AS "Unique",
       x.indisprimary                                        AS "Primary",
       x.indisclustered                                      AS "Clustered",
       x.indnatts                                            AS "N Cols",
       pg_catalog.obj_description(x.indexrelid, 'pg_class')  AS "Comment"
FROM   pg_index x
   JOIN   pg_class c ON c.oid = x.indrelid
   JOIN   pg_class i ON i.oid = x.indexrelid
   LEFT JOIN pg_namespace n ON n.oid = c.relnamespace
   LEFT JOIN pg_tablespace t ON t.oid = i.reltablespace
WHERE c.relkind = 'r'::"char"
AND   i.relkind = 'i'::"char"
AND i.relname NOT IN
(
    SELECT
        cr.constraint_name
    FROM
        information_schema.table_constraints cr
    WHERE
        n.nspname = cr.table_schema
    AND c.relname = cr.table_name
)
AND   n.nspname LIKE '${schema}'
AND   c.relname LIKE '${table}'
ORDER BY n.nspname, i.relname
            ]]>
         </SQL>
      </Command>

      <Command id="postgresql.getIndexSource">
         <SQL>
            <![CDATA[
SELECT pg_get_indexdef(i.oid) AS indexdef
FROM   pg_index x JOIN pg_class c ON c.oid = x.indrelid
   JOIN   pg_class i ON i.oid = x.indexrelid
   LEFT JOIN pg_namespace n ON n.oid = c.relnamespace
   LEFT JOIN pg_tablespace t ON t.oid = i.reltablespace
WHERE c.relkind = 'r'::"char" AND i.relkind = 'i'::"char"
AND   i.relname = '${indexname}' AND n.nspname LIKE '${schema}'
            ]]>
         </SQL>
      </Command>

      <Command id="postgresql.getTriggers">
         <SQL>
            <![CDATA[
SELECT DISTINCT
       trigger_name         AS "Trigger Name",
       trigger_catalog      AS "Trigger Catalog",
       trigger_schema       AS "Trigger Schema",
       action_orientation   AS "Action Orientation",
            ]]>
        <If test="(#dm.getDatabaseMajorVersion() gte 9 and
                   #dm.getDatabaseMinorVersion() gte 1)">
            <![CDATA[
       action_timing        AS "Condition Timing",
            ]]>
       </If>
       <Else>
            <![CDATA[
       condition_timing     AS "Condition Timing",
            ]]>
       </Else>
            <![CDATA[
       event_object_catalog AS "Event Object Catalog",
       event_object_schema  AS "Event Object Schema",
       event_object_table   AS "Event Object Table"
FROM information_schema.triggers 
WHERE trigger_schema LIKE '${schema}'
AND event_object_table LIKE '${tableNamePattern}'
ORDER BY 1
            ]]>
         </SQL>
      </Command>

      <Command id="postgresql.getTriggerSource">
         <SQL>
            <![CDATA[
SELECT p.prosrc
FROM pg_trigger trg, pg_class tbl, pg_proc p
WHERE trg.tgrelid = tbl.oid
AND trg.tgfoid = p.oid
AND trg.tgname = '${trigname}'
            ]]>
         </SQL>
      </Command>

      <Command id="postgresql.getFunctions">
         <SQL>
            <![CDATA[
SELECT p.proname AS "Function Name",
       n.nspname AS "Schema Name",
      CASE WHEN p.proretset THEN 'setof ' ELSE '' END ||
      pg_catalog.format_type(p.prorettype, NULL) AS "Result data type",
      pg_catalog.oidvectortypes(p.proargtypes) AS "Argument data types",
      r.usename AS "Owner",
      l.lanname AS "Language",
      pg_catalog.obj_description(p.oid, 'pg_proc') AS "Comment"
FROM pg_catalog.pg_proc p
   LEFT JOIN pg_catalog.pg_namespace n ON n.oid = p.pronamespace
   LEFT JOIN pg_catalog.pg_language l ON l.oid = p.prolang
   LEFT JOIN pg_catalog.pg_user r ON r.usesysid = p.proowner
WHERE p.prorettype <> 'pg_catalog.cstring'::pg_catalog.regtype
   AND (p.proargtypes[0] IS NULL
      OR   p.proargtypes[0] <> 'pg_catalog.cstring'::pg_catalog.regtype)
   AND NOT p.proisagg
   AND n.nspname LIKE '${schema}'
ORDER BY 2, 1, 3, 4
            ]]>
         </SQL>
      </Command>

      <Command id="postgresql.getFunctionSource">
         <SQL>
            <![CDATA[
SELECT p.prosrc as "Source code"
FROM pg_catalog.pg_proc p
   LEFT JOIN pg_catalog.pg_namespace n ON n.oid = p.pronamespace
WHERE n.nspname = '${schema}'
AND p.proname = '${funcname}';
            ]]>
         </SQL>
      </Command>

      <Command id="postgresql.getSequences">
         <SQL>
            <![CDATA[
SELECT c.relname                                                           AS "Sequence Name",
       n.nspname                                                           AS "Schema Name",
       c.oid                                                               AS "Rel Id",
       (pg_stat_get_blocks_fetched(c.oid) - pg_stat_get_blocks_hit(c.oid)) AS "Blocks Read",
       pg_stat_get_blocks_hit(c.oid)                                       AS "Blocks Hit",
